import 'package:flutter/material.dart';

const COLOR_1 = Color(0xffA6623B);
const COLOR_2 = Color(0xff28969C);
const COLOR_3 = Color(0xffA1ADAE);
const COLOR_4 = Color(0xffBACED1);
const COLOR_5 = Color(0xff032E31);
const COLOR_6 = Color(0xffF6F6F6);

// MAIN PAGE
const MAIN_PAGE_ACCENT_COLOR = COLOR_6;
const MAIN_PAGE_TEXT_COLOR = COLOR_2;

// CURRENT LOCATION
const CURRENT_LOCATION_PRIMARY_TEXT_COLOR = COLOR_6;
const CURRENT_LOCATION_PRIMARY_DARK_TEXT_COLOR = COLOR_5;
const CURRENT_LOCATION_SECONDARY_TEXT_COLOR = COLOR_3;
const CURRENT_LOCATION_BACKGROUND_COLOR = COLOR_2;
const CURRENT_LOCATION_BACKGROUND_COLOR_LIGHT = COLOR_6;
const CURRENT_LOCATION_ACCENT_COLOR = COLOR_6;

// STARTING LOCATION
const STARTING_LOCATION_PRIMARY_TEXT_COLOR = COLOR_6;
const STARTING_LOCATION_SECONDARY_TEXT_COLOR = COLOR_3;
const STARTING_LOCATION_BACKGROUND_COLOR = COLOR_4;
const STARTING_LOCATION_BACKGROUND_COLOR_LIGHT = COLOR_6;
const STARTING_LOCATION_PRIMARY_DARK_TEXT_COLOR = COLOR_3;

// SETTINGS
const SETTINGS_LOCATION_BACKGROUND_COLOR_LIGHT = COLOR_6;
const SETTINGS_PRIMARY_TEXT_COLOR = COLOR_2;
const SETTINGS_ACCENT_COLOR = COLOR_2;
